import { useCallback, useEffect, useMemo, useState } from 'react';
import { Bell, Check, CheckCheck, Filter, Trash2 } from 'lucide-react';
import {
  deleteNotification,
  getMyNotifications,
  getNotification,
  markAllAsRead,
  markAsRead,
} from '../../api/notifications';
import Card from '../../components/common/Card';
import Button from '../../components/common/Button';
import Spinner from '../../components/common/Spinner';
import EmptyState from '../../components/common/EmptyState';
import Pagination from '../../components/common/Pagination';
import Modal from '../../components/common/Modal';
import {
  emitNotificationsSync,
  formatDate,
  getNotificationIcon,
  getNotificationLabel,
  NOTIFICATION_TYPES,
} from '../../utils/constants';
import {
  extractApiData,
  normalizeNotification,
  normalizePaginatedData,
} from '../../utils/apiData';

const toNotificationsPage = (payload) => normalizePaginatedData(payload, normalizeNotification);

export default function AdminNotifications() {
  const [data, setData] = useState({ content: [], totalPages: 0, currentPage: 0 });
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(0);
  const [unreadOnly, setUnreadOnly] = useState(false);
  const [typeFilter, setTypeFilter] = useState('');
  const [selectedNotification, setSelectedNotification] = useState(null);
  const [detailLoading, setDetailLoading] = useState(false);

  const load = useCallback(() => {
    setLoading(true);
    getMyNotifications({ page, size: 25, unreadOnly })
      .then((res) => {
        setData(toNotificationsPage(extractApiData(res)));
      })
      .catch((err) => {
        console.error('Failed to load admin notifications:', err);
      })
      .finally(() => setLoading(false));
  }, [page, unreadOnly]);

  useEffect(() => {
    load();
  }, [load]);

  const filteredNotifications = useMemo(() => {
    if (!typeFilter) return data.content || [];
    return (data.content || []).filter((item) => item.type === typeFilter);
  }, [data.content, typeFilter]);

  const unreadCount = filteredNotifications.filter((item) => !item.read).length;

  const updateNotification = (id, updater) => {
    setData((prev) => ({
      ...prev,
      content: prev.content.map((item) => (item.id === id ? updater(item) : item)),
    }));
  };

  const handleMarkRead = async (id, options = {}) => {
    try {
      await markAsRead(id);
      updateNotification(id, (item) => ({ ...item, read: true, isRead: true }));
      if (!options.silent) emitNotificationsSync();
    } catch (err) {
      console.error('Failed to mark notification as read:', err);
      if (!options.silent) alert('Failed to mark notification as read');
    }
  };

  const handleMarkAll = async () => {
    try {
      await markAllAsRead();
      setData((prev) => ({
        ...prev,
        content: prev.content.map((item) => ({ ...item, read: true, isRead: true })),
      }));
      emitNotificationsSync();
    } catch (err) {
      console.error('Failed to mark all notifications as read:', err);
      alert('Failed to mark all notifications as read');
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Delete this notification?')) return;

    try {
      await deleteNotification(id);
      setData((prev) => ({
        ...prev,
        content: prev.content.filter((item) => item.id !== id),
      }));
      if (selectedNotification?.id === id) setSelectedNotification(null);
      emitNotificationsSync();
    } catch (err) {
      console.error('Failed to delete notification:', err);
      alert('Failed to delete notification');
    }
  };

  const handleOpenDetails = async (notification) => {
    setSelectedNotification(notification);
    setDetailLoading(true);

    try {
      const res = await getNotification(notification.id);
      const detailedNotification = normalizeNotification(extractApiData(res) || notification);
      setSelectedNotification(detailedNotification);
      if (!detailedNotification.read) {
        await handleMarkRead(detailedNotification.id, { silent: true });
        setSelectedNotification((prev) => (
          prev ? { ...prev, read: true, isRead: true } : prev
        ));
        emitNotificationsSync();
      }
    } catch (err) {
      console.error('Failed to load notification details:', err);
    } finally {
      setDetailLoading(false);
    }
  };

  return (
    <div>
      <div className="flex items-center justify-between mb-5 gap-3 flex-wrap">
        <div>
          <h1 className="text-lg font-semibold">Notifications</h1>
          <p className="text-sm text-text-muted mt-0.5">
            Review updates generated by booking and ticket activity.
          </p>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          {unreadCount > 0 && (
            <span className="px-2.5 py-1 bg-danger text-white text-xs font-medium rounded-full">
              {unreadCount} unread in view
            </span>
          )}
          <Button size="sm" variant="secondary" onClick={handleMarkAll} disabled={(data.content || []).length === 0}>
            <CheckCheck size={13} className="mr-1" />
            Mark all read
          </Button>
        </div>
      </div>

      <Card className="p-4 mb-4">
        <div className="flex flex-wrap items-center gap-3">
          <div className="flex items-center gap-2">
            <Filter size={14} className="text-text-muted" />
            <select
              value={typeFilter}
              onChange={(event) => {
                setTypeFilter(event.target.value);
                setPage(0);
              }}
              className="text-xs border border-border rounded-md px-2 py-1.5 bg-white"
            >
              <option value="">All Types</option>
              {NOTIFICATION_TYPES.map((type) => (
                <option key={type.value} value={type.value}>{type.label}</option>
              ))}
            </select>
          </div>
          <label className="flex items-center gap-1.5 text-xs cursor-pointer">
            <input
              type="checkbox"
              checked={unreadOnly}
              onChange={(event) => {
                setUnreadOnly(event.target.checked);
                setPage(0);
              }}
              className="accent-primary-600"
            />
            Unread only
          </label>
        </div>
      </Card>

      <Card>
        {loading ? (
          <div className="flex justify-center py-16"><Spinner className="h-8 w-8" /></div>
        ) : filteredNotifications.length === 0 ? (
          <EmptyState message="No notifications found" icon={Bell} />
        ) : (
          <>
            <div className="divide-y divide-border">
              {filteredNotifications.map((notification) => (
                <div
                  key={notification.id}
                  className={`px-4 py-3.5 flex gap-3 hover:bg-surface-alt/50 transition-colors ${!notification.read ? 'bg-primary-50/30' : ''}`}
                >
                  <button
                    type="button"
                    onClick={() => handleOpenDetails(notification)}
                    className="flex gap-3 flex-1 min-w-0 text-left"
                  >
                    <span className="text-xs font-semibold shrink-0 mt-0.5 text-text-muted">
                      {getNotificationIcon(notification.type)}
                    </span>
                    <div className="flex-1 min-w-0">
                      <p className={`text-sm ${!notification.read ? 'font-medium text-text-primary' : 'text-text-secondary'}`}>
                        {notification.message}
                      </p>
                      <p className="text-xs text-text-muted mt-1">
                        {getNotificationLabel(notification.type)} - {formatDate(notification.createdAt)}
                      </p>
                    </div>
                  </button>
                  <div className="flex items-center gap-1 shrink-0">
                    {!notification.read && (
                      <button
                        onClick={() => handleMarkRead(notification.id)}
                        className="p-1.5 rounded hover:bg-surface-alt text-text-muted hover:text-primary-600 transition-colors"
                        title="Mark as read"
                      >
                        <Check size={14} />
                      </button>
                    )}
                    <button
                      onClick={() => handleDelete(notification.id)}
                      className="p-1.5 rounded hover:bg-surface-alt text-text-muted hover:text-danger transition-colors"
                      title="Delete"
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>
                </div>
              ))}
            </div>
            <div className="px-4 pb-3">
              <Pagination
                currentPage={data.currentPage || 0}
                totalPages={data.totalPages || 0}
                onPageChange={setPage}
              />
            </div>
          </>
        )}
      </Card>

      <Modal
        open={!!selectedNotification}
        onClose={() => setSelectedNotification(null)}
        title={selectedNotification ? getNotificationLabel(selectedNotification.type) : 'Notification'}
        size="md"
      >
        {detailLoading ? (
          <div className="flex justify-center py-8"><Spinner className="h-6 w-6" /></div>
        ) : selectedNotification ? (
          <div className="space-y-4">
            <div className="flex items-start gap-3">
              <span className="text-xs font-semibold text-text-muted mt-1">
                {getNotificationIcon(selectedNotification.type)}
              </span>
              <div>
                <p className="text-sm font-medium text-text-primary">{selectedNotification.message}</p>
                <p className="text-xs text-text-muted mt-1">{formatDate(selectedNotification.createdAt)}</p>
              </div>
            </div>
            <div className="rounded-md bg-surface-alt px-3 py-3">
              <p className="text-xs uppercase tracking-wide text-text-muted mb-1">Details</p>
              <p className="text-sm text-text-secondary whitespace-pre-wrap">
                {selectedNotification.content || selectedNotification.message}
              </p>
            </div>
            <div className="flex justify-end gap-2">
              {!selectedNotification.read && (
                <Button
                  size="sm"
                  variant="secondary"
                  onClick={() => handleMarkRead(selectedNotification.id)}
                >
                  Mark as read
                </Button>
              )}
              <Button
                size="sm"
                variant="danger"
                onClick={() => handleDelete(selectedNotification.id)}
              >
                Delete
              </Button>
            </div>
          </div>
        ) : null}
      </Modal>
    </div>
  );
}
